# https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
# This is an example of ingress route please change the sub-domain as per requirements. 
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
  annotations:
        kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  tls:
    secretName: local-techchad2022-rocks-staging
  routes:
    - kind: Rule
      match: Host(`traefik.example.com`)
      middlewares:
      - name: traefik-dashboard-auth
        namespace: kube-system
      services:
      - kind: TraefikService
        name: api@internal
