
globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=DEBUG"

deployment:
  enabled: true
  replicas: 1
  annotations: {}
  podAnnotations: {}
  AdditionalContainers: {}
  initContainers: []

ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    protocol: TCP
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  LoadBalancerIP: 192.168.10.30
