# This is the certificate for production environments.
# Please update the dnsNames.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-techchad2022-rocks
  namespace: default
spec:
  secretName: local-techchad2022-rocks-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
  - "*.example.com"
