# This is the secret that cert-manager uses to authenticate with cloudflare for domain validation.
# Please update the api-token from api key obtained from cloudflare.
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: <>